<?php
require_once('tcpdf/tcpdf.php'); // or 'vendor/autoload.php' if composer installed

// create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator('My App');
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Test PDF');
$pdf->SetSubject('TCPDF Test');

// set default header data
$pdf->SetHeaderData('', 0, 'Test PDF Header', 'Generated by TCPDF');

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// add a page
$pdf->AddPage();

// set font
$pdf->SetFont('helvetica', '', 12);

// add some text
$html = '<h1>Hello TCPDF!</h1><p>This is a simple test PDF generated by TCPDF.</p>';
$pdf->writeHTML($html, true, false, true, false, '');

// output the PDF (I for inline view, D for download)
$pdf->Output('test_tcpdf.pdf', 'I');

// trying to print pdf page using php and tpdf

